### ISSUE TITLE
Redis Horizon queuing jobs

### ISSUE THREAD

**Issue by LocalHeroPro** [KKSzymanowski/laravel-6-firebird#6]
When I run some code using `sync` connection - all works as expected.
```php
StoreToFirebird::dispatch()
    ->allOnConnection('sync')
    ->allOnQueue('default');
```
When I using real scenario by adding job to queue
```php
StoreToFirebird::dispatch()
    ->allOnConnection('redis')
    ->allOnQueue('default');
```
I have that error in `failed_jobs` table:
```
PDOException: SQLSTATE[HY000] [335544472] Your user name and password are not defined. Ask your database administrator to set up a Firebird login. in /var/www/cpt.local/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
Stack trace:
#0 /var/www/cpt.local/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
#1 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct()
#2 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
#3 /var/www/cpt.local/html/vendor/kkszymanowski/laravel-6-firebird/src/FirebirdConnector.php(26): Illuminate\Database\Connectors\Connector->createConnection()
#4 /var/www/cpt.local/html/vendor/kkszymanowski/laravel-6-firebird/src/FirebirdServiceProvider.php(29): Firebird\FirebirdConnector->connect()
#5 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(271): Firebird\FirebirdServiceProvider->Firebird\{closure}()
#6 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(76): Illuminate\Database\Connectors\ConnectionFactory->createConnection()
#7 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(50): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection()
#8 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(131): Illuminate\Database\Connectors\ConnectionFactory->make()
#9 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(86): Illuminate\Database\DatabaseManager->makeConnection()
#10 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1255): Illuminate\Database\DatabaseManager->connection()
#11 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1221): Illuminate\Database\Eloquent\Model::resolveConnection()
#12 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\Database\Eloquent\Model->getConnection()
#13 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(968): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#14 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1004): Illuminate\Database\Eloquent\Model->newModelQuery()
#15 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(957): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#16 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(947): Illuminate\Database\Eloquent\Model->newQuery()
#17 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(461): Illuminate\Database\Eloquent\Model::query()
```
Other queues using PostgreSQL working as expected.

**Comment by KKSzymanowski** [comment]
```
Your user name and password are not defined.
```

This means your username or password is incorrect. Go to `vendor/kkszymanowski/laravel-6-firebird/src/FirebirdConnector.php` and add `dd($config)` to the top of the `connect` method to see if you provide the credentials you think you provide. Maybe running on a redis queue uses a separate env where you haven't defined the proper username and password.

**Comment by KKSzymanowski** [comment]
Have you been able to solve this problem?

**Comment by LocalHeroPro** [comment]
It turned out that it was necessary to restart Horizon.
Horizon keep config in himself and no matter you run `sudo php artisan config:clear` or `cache:clear` or manually delete cache files ...
So only restart horizon is needed, because it have independent cache for config from `.env` file.

**Comment by KKSzymanowski** [comment]
I think that it's not really accurate to say Horizon has independent cache. It's just a single instance of Laravel kept running, that's why the config doesn't change when you change the files.
It's like running `php artisan tinker` and then changing the config. If you keep it running it will still see old data. Same with deployments and `composer install` - you have to restart Horizon every time you update the project files.
